# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pipeline Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    #- run: sudo apt-get install google-chrome-stable
    # - run: npm test
    # env:
    #   CI: true
    - name: NPM Test
      - run:
          export CHROME_BIN=/usr/bin/chromium-browser && CI=true npm run test-headless
        env:
          CI: true

    # - run: sudo apt install chromium-browser
    #   - name: Install dependencies
    #     run: npm ci

    #   - name: NPM Test
    #     run: |
    #       export CHROME_BIN=/usr/bin/chromium-browser
    #       CI=true npm run test-headless
    #     env:
    #       CI: true

    - name:  Quality Gate
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


    - name: "Check Quality Gate" #can also use simple or double quotes
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

